import '@fortawesome/fontawesome-svg-core/styles.css'
import {config} from '@fortawesome/fontawesome-svg-core'
config.autoAddCss=false;
import type { Metadata } from "next";
import { dark } from '@clerk/themes';
import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({ subsets: ["latin"] ,
  weight:['400','500','600','700'],
  variable:'--font-poppins'
 });

export const metadata: Metadata = {
  title: "Events",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark
    }}>
      <html lang="en">
      <body className={poppins.variable}>{children}</body>
    </html>
    </ClerkProvider>
    
  );
}
